include:
  - project: freedesktop/ci-templates
    ref: 290b79e0e78eab67a83766f4e9691be554fc4afd
    file:
    - templates/ubuntu.yml

stages:
  - container prep
  - build

.common_variables:
  variables:
    FDO_UPSTREAM_REPO: mobile-broadband/libmbim
    FDO_DISTRIBUTION_VERSION: '20.04'
    FDO_DISTRIBUTION_TAG: '2021-11-05.1'
    FDO_DISTRIBUTION_PACKAGES: ca-certificates git gcc libgirepository1.0-dev
                               libglib2.0-dev gtk-doc-tools libglib2.0-doc
                               gobject-introspection bash-completion valac
                               meson ninja-build help2man

build container:
  extends:
  - .fdo.container-build@ubuntu
  - .common_variables
  stage: container prep
  only:
    - main
    - merge_requests
    - tags
    - schedules

build-no-introspection:
  stage: build
  extends:
  - .fdo.distribution-image@ubuntu
  - .common_variables
  only:
    - main
    - merge_requests
    - tags
    - schedules
  script:
    - meson setup build --prefix=/usr -Dwerror=true -Dintrospection=false
    - ninja -C build
    - ninja -C build install

build-debug:
  stage: build
  extends:
  - .fdo.distribution-image@ubuntu
  - .common_variables
  only:
    - main
    - merge_requests
    - tags
    - schedules
  script:
    - meson setup build --buildtype=debug --prefix=/usr -Dgtk_doc=true -Dwerror=true
    - ninja -C build
    - ninja -C build install
    - ninja -C build dist
    - ninja -C build uninstall

build-no-deprecated:
  stage: build
  extends:
  - .fdo.distribution-image@ubuntu
  - .common_variables
  only:
    - main
    - merge_requests
    - tags
    - schedules
  script:
    - CFLAGS="-DMBIM_DISABLE_DEPRECATED" meson setup build --prefix=/usr -Dwerror=true -Dintrospection=false
    - ninja -C build
    - ninja -C build install

build-release:
  stage: build
  extends:
  - .fdo.distribution-image@ubuntu
  - .common_variables
  only:
    - main
    - merge_requests
    - tags
    - schedules
  script:
    - meson setup build --buildtype=release --prefix=/usr -Dgtk_doc=true -Dwerror=true
    - ninja -C build
    - ninja -C build install
    - ninja -C build dist
    - ninja -C build uninstall
